carro/urls.py
from django.urls import path

from . import views

app_name = 'carro'
urlpatterns = [
    path('agregar/<int:product_id>/', views.agregar_producto, name='agregar'),
    path('agregar_cantidad/<int:product_id>/<int:quantity>/', views.agregar_producto_cantidad, name='agregar_cantidad'),
    path('agregar_carro/<int:product_id>/', views.agregar_producto_desde_carro, name='agregar_carro'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:product_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    path('carro/', views.ver_carro, name='ver_carro'),

    path('contar/', views.contar_carro, name='contar_carro'),



]

micro_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuario.views import MyPasswordChangeView
from . import views

urlpatterns = [

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='usuario/reset_pass/password_reset.html'), name='password_reset'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='usuario/reset_pass/complete.html'), name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='usuario/reset_pass/confirm.html'), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='usuario/reset_pass/done.html'), name='password_reset_done'),

    path('administrador/', admin.site.urls, name='admin'),
    path('', include('products.urls')),
    path('carro/', include('carro.urls')),
    path('usuario/', include('usuario.urls')),
    path('extra/', include('extra.urls')),
    path('ventas/', include('ventas.urls')),
    path('pedidos/', include('pedidos_stripe.urls')),



    path('<int:user_id>/password/', MyPasswordChangeView.as_view(),
             name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [

    path('get_hijas/', views.get_hijas, name='get_hijas'),

    path('create/', views.product_create_view, name='create'),
    path('mis_productos_table/', views.mis_productos_table, name='mis_productos'),
    path('', views.product_list_view, name='list'),
    path('filter/<int:provider_id>/', views.product_list_view, name='filter_by_provider'),
    path('like_filter/<int:provider_id>/', views.product_list_view, name='filter_by_provider'),
    path('promotion/<int:promotion_id>/', views.product_list_view, name='promotion'),



    path('<slug:handle>/', views.product_detail_view, name='detail'),
    path('<slug:handle>/manage/', views.product_manage_detail_view, name='manage'),
    path('<slug:handle>/download/<int:pk>', views.product_attachment_download_view, name='download'),

    path('search/', views.search, name='search'),

    # path('eliminar/<slug:handle>/', views.delete_product, name='eliminar'),


    #Crear oferta
    path('crear_oferta/<int:product_id>/', views.crear_oferta, name='crear_oferta'),
    path('eliminar_oferta/<int:product_id>/', views.eliminar_oferta, name='eliminar_oferta'),
    path('rate_product/<int:product_id>/', views.rate_product, name='rate_product'),

    path('like_product/<int:product_id>/', views.like_product, name='like'),
    path('dislike_product/<int:product_id>/', views.dislike_product, name='dislike'),




]

products/views.py
import os

import requests
from django.core.checks import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
import mimetypes
from django.http import FileResponse, HttpResponseBadRequest, JsonResponse, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import  User
from stripe import APIConnectionError

from carro.carro import Carro
from extra.models import Promocion
from micro_ecommerce import settings

from usuario.decorator import role_required
# Create your views here.
from .form import ProductUpdateForm, ProductAttachmentInlineFormSet, ProductOfferForm, ProductForm
from .models import Product, ProductImage, ProductView, Rating, ProductOffer, Rating_product, Likes, \
     Venta, Category

from django.db.models import Sum, Count, Q
from django.utils import timezone
from datetime import datetime, timedelta

from django.db import models



@role_required(['Proveedor'])
def product_create_view(request):
    context={}
    clasificacion_hija = None
    form = ProductForm(request.POST or None,  request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            try:
                clasi = int(request.POST.get('clasificacion'))
            except:
                clasi = None
            try:
                clasi2 = int(request.POST.get('category'))
            except:
                clasi2 = None
            obj = form.save(commit=False)
            if request.user.is_authenticated:
                obj.user = request.user
                try:
                    obj.active = True
                    if clasi:
                        new_category = get_object_or_404(Category, id=clasi)
                        print(new_category)
                    else:
                        new_category = get_object_or_404(Category, id=clasi2)
                    obj.category = new_category

                    obj.save()
                    if not hasattr(obj, 'rating_product'):
                        Rating_product.objects.create(product=obj)
                    form.save_m2m()
                except Exception as e:
                    # Manejo de otras excepciones   
                    conexion_error =  f'Ocurrió un error inesperado: {str(e)}'
                    context = {
                        'conexion_error': conexion_error,
                        'form': form
                    }
                    return render(request, 'products/create.html', context)

                if request.POST.get('action') == 'save_and_add':
                    # Redirigir al mismo formulario para agregar otro producto
                    return redirect('products:create')
                else:
                    # Redirigir a otra página, por ejemplo, la lista de productos
                    return redirect(obj.get_manage_url())
            else:
                form.add_error(None,"Your  must be looged in to create product")
        else:
            conexion_error = form.errors

            context['conexion_error'] = conexion_error
    context['form'] = form
    return render(request, 'products/create.html',context)


from django.core.serializers import serialize

# @cache_page(60 * 15)  # 15 minutos
def product_list_view(request,provider_id=None,promotion_id=None):
    filtrado = False
    object_list = Product.objects.all()
    descuento = request.GET.get('descuento')
    if descuento:
        filtrado=True
        object_list = Product.objects.filter(offer__is_active=True)

    object_list = object_list.filter(active=True)

    no_nuevos=False



    # productos mas vendidos


    top_productos = sorted(object_list, key=lambda p: p.total_ventas(), reverse=True)[:5]
    # ------------------------------------------------------------------------------





    # ---------------------------------------------------------------




    # ofertas premuim
    premium_offer = ProductOffer.objects.filter(is_premium=True,is_active=True)
    premium_offer = sorted(premium_offer, key=lambda offer: offer.product.count_views(), reverse=True)
    # ---------------------------------------------------------------

    # productos mejor evaluados
    top_rated = Product.objects.filter(active=True).order_by('-rating_product__average_rating')[:10]
    # ---------------------------------------------------------------

    # productos nuevos
    today = timezone.now().date()
    seven_days_ago = today - timedelta(days=7)
    new_products = Product.objects.filter(timestamp__gte=seven_days_ago,active=True)[:10]

    # productos gustados por el usuario
    if not new_products.exists():
        # Si no hay productos nuevos, obtiene el top 5 de los productos con más likes
        new_products = Product.objects.filter(active=True).annotate(
            like_count=models.Count('like')
        ).order_by('-like_count')[:10]
        no_nuevos=True
    else:
        pass
    # ---------------------------------------------------------------



    promociones = Promocion.objects.all()

    # filtrar por la promocion
    if promotion_id:
        filtrado=True
        promotion = get_object_or_404(Promocion, id=promotion_id)
        object_list = promotion.productos.filter(active=True)
    # ------------------------------------------------------------



    # Obtener los productos y contar las vistas de la última semana
    week_ago = timezone.now() - timedelta(days=7)
    trending_products = (
        Product.objects.annotate(
            view_count=models.Count('productview', filter=models.Q(productview__timestamp__gte=week_ago,active=True)))
        .order_by('-view_count')[:10]  # Limitar a los 10 más vistos
    )
    # ---------------------------------------------------------------

    if provider_id:
        filtrado=True
        obj = get_object_or_404(User, id=provider_id)
        object_list = object_list.filter(user=obj)

    category = Category.get_root_nodes()
    carro = Carro(request)
    category = sorted(category, key=lambda x: x.search_count, reverse=True)




    # Handle search query
    search_query = request.GET.get('search')
    if search_query:
        filtrado=True
        object_list = object_list.filter(
            Q(keywords__icontains=search_query) | Q(name__icontains=search_query)
        )

    # Handle classification filter
    classification_id = request.GET.get('category')
    if classification_id:
        filtrado = True
        # Obtener la categoría seleccionada
        categoria_seleccionada = Category.objects.get(pk=classification_id)
        categoria_seleccionada.increment_search_count()
        print(categoria_seleccionada.search_count)
        # Filtrar los productos por la categoría y sus descendientes
        descendants = categoria_seleccionada.get_descendants()
        object_list1 = object_list.filter(category__in=descendants)
        object_list2 = object_list.filter(category=categoria_seleccionada)
        object_list = object_list1.union(object_list2)

    liked = request.GET.get('liked_product')
    if liked:
        filtrado=True
        object_list = Product.objects.filter(like__user=request.user)

    classification_id_padre = request.GET.get('classification_id_padre')
    if classification_id_padre:
        filtrado=True
        object_list = object_list.filter(clasificaciones_padre__id=classification_id_padre)






    # # Paginar los productos
    # page_size = 20  # Número de solicitudes por página
    # paginator = Paginator(object_list, page_size)
    # page_number = request.GET.get('page', 1)
    #
    # try:
    #     page_solicitudes = paginator.page(page_number)
    # except PageNotAnInteger:
    #     page_solicitudes = paginator.page(1)
    # except EmptyPage:
    #     page_solicitudes = paginator.page(paginator.num_pages)
    # products_data = serialize('json', object_list)


    for cate in category:
        # Contar productos en la categoría y sus subcategorías
        cate.product_count = (
                cate.products.count() +
                cate.get_children().aggregate(total=Count('products'))['total'] or 0
        )
    # Ordenar el object_list por el conteo de vistas
    object_list = (
        Product.objects.filter(id__in=object_list.values_list('id', flat=True))
        .order_by('-views')  # Ordenar por el campo views
    )

    context = {
        'object_list': object_list[:50],
        'carro': carro,
        'category': category,
        'promociones': promociones,
        'top_products': top_productos,
        'new_products': new_products,
        'trending_products': trending_products,
        'top_rated': top_rated,
        'premium_offer': premium_offer,
        'filtrado': filtrado,
        'no_nuevos': no_nuevos,

    }
    return render(request,"products/list.html",context)




@role_required(['Proveedor'])
def product_manage_detail_view(request,handle=None):
    obj = get_object_or_404(Product,handle=handle)
    # attachments = ProductImage.objects.filter(product=obj)
    is_manager = False
    clasificacion_hija = None
    clasificacion_padre = None

    if request.user.is_authenticated:
        is_manager = obj.user == request.user
    context = {"object": obj}

    if not is_manager:
        return HttpResponseBadRequest("No eres proveedor de este producto")
    form = ProductUpdateForm(request.POST or None,  request.FILES or None, instance=obj)

    # formset = ProductAttachmentInlineFormSet(request.POST or None,request.FILES or None,queryset=attachments)
    if request.method == 'POST':
        if request.POST.get('category'):
            try:
                clasi = int(request.POST.get('clasificacion'))
                clasificacion_hija = get_object_or_404(Category, pk=clasi)
                # clasificacion_hija = root_category.get_children()
            except:

templates/products/category2.html
<style>
.category-img-box {
    width: 90px; /* Ajusta según tus necesidades */
    height: 70px; /* Ajusta según tus necesidades */
    background-size: cover; /* Para que la imagen cubra todo el contenedor */
    background-position: center; /* Centra la imagen */
    overflow: hidden; /* Oculta cualquier contenido que sobresalga */
}

</style>

<div class="category">

    <div class="container">

        <div class="category-item-container has-scrollbar">

            {% for cate in category %}
                {% if cate.has_products  %}
                    <div class="category-item">


                        <div class="category-img-box" style="{% if cate.image %} background-image: url('{{ cate.image.url }}'); {% endif %}">
                            <a href="{% url 'products:list' %}?category={{ cate.pk }}">
                                <!-- Contenido adicional si es necesario -->

                            </a>
                        </div>


                        <div class="category-content-box">

                            <div class="category-content-flex">
                                <h3 class="category-item-title">{{ cate }}</h3>


                                    <p class="category-item-amount">{{ cate.product_count }}</p>

                            </div>

                            <a href="{% url 'products:list' %}?category={{ cate.pk }}" class="category-btn">Mostrar</a>

                        </div>

                    </div>
                {% endif %}
            {% endfor %}

        </div>

    </div>

</div>

templates/products/list-card.html
<div style="display: flex; align-items: center; background-color: #f9fafb; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  {% if object.image %}
  <a href="{{ object.get_absolute_url }}">
    <img style="width: 100%; max-width: 256px; border-radius: 8px 0 0 8px; object-fit: cover;" src="{{ object.image.url }}" alt="{{ object.name }}">
  </a>
  {% endif %}
  <div style="padding: 20px;">
    <h3 style="font-size: 1.25rem; font-weight: bold; color: #111827;">
      <a href="{{ object.get_absolute_url }}" style="text-decoration: none; color: inherit;">{{ object.name }}</a>
    </h3>
    <span style="font-size: 1.875rem; font-weight: bold; color: #111827;">{{ object.price }} cup</span>
    <span style="color: #6b7280;">{{ object.handle }}</span>
    <p style="margin-top: 12px; margin-bottom: 16px; color: #6b7280;">Disponibles: {{ object.supply }}</p>
    {% if object.user != request.user %}
      {% if object.supply != 0 %}
    <form action="{% url 'carro:agregar' object.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="product_id" value="{{ object.id }}">

      <div style="display: flex; align-items: center; margin-bottom: 16px;">
        <label for="quantity" style="margin-right: 8px; color: #374151;">Cantidad:</label>
        <input type="number" id="quantity" name="quantity" min="1" max="{{ object.supply }}" value="1" style="background-color: #f9fafb; border: 1px solid #d1d5db; color: #111827; border-radius: 4px; padding: 8px; width: 100%;" required>
      </div>
      <button type="submit" style="background-color: #ff7f50; color: white; border: none; border-radius: 4px; padding: 10px 20px; font-size: 14px; cursor: pointer; transition: background-color 0.3s;">
        Agregar al carrito
      </button>
    </form>
      {% endif %}
    {% endif %}
  </div>
</div>

templates/products/product_classifications.html
  <form method="get" action="{% url 'products:list' %}">

<div class="flex items-center">
                        <label for="search" class="sr-only">Buscar productos</label>
                        <div class="relative w-full">
                            <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                            </div>
                            <input type="text" id="search" name="search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-text-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Buscar productos" >
                        </div>
                        <button type="submit" class="py-2.5 px-5 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Buscar</button>
                    </div>

<nav aria-label="Breadcrumb" class="relative flex items-center py-3 px-4 bg-gray-100 dark:bg-gray-800">
  <ol class="inline-flex items-center space-x-1 md:space-x-3">

   <button type="submit" class="breadcrumb-link text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white" data-classification-id="{{ classification.id }}">
           Todos
          </button>
  <li>
            <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
            </svg>
          </li>
    {% for classification in classifications %}
      {% if not classification.parent %}
        <li class="group relative">
          <button type="submit"  class="breadcrumb-link text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white" name="classification_id_padre" value="{{ classification.id }}">
            {{ classification.nombre }}
          </button>

          {% if classification.hijos.all %}

            <div class="absolute z-10 hidden group-hover:block w-48 bg-white dark:bg-gray-800 rounded-lg shadow-lg">
              <ul class="py-2">
                {% for child_classification in classification.hijos.all %}
                    {% if child_classification.pro.exists  %}
                  <li>
                    <button type="submit"  class="block px-4 py-2 text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700" name="classification_id" value="{{ child_classification.id }}" >
                      {{ child_classification.nombre }}
                    </button>

                  </li>
                     {% endif %}
                {% endfor %}

              </ul>
            </div>
          {% endif %}

        </li>

        {% if not forloop.last %}
          <li>
            <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
            </svg>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
  </ol>
</nav>
</form>

templates/products/productosFeatured.html
 <!--
            - PRODUCT FEATURED
          -->

          <div class="product-featured">

            <h2 class="title">Ofertas Premium</h2>

            <div class="showcase-wrapper has-scrollbar" id="carousel">

                {% for offer in  premium_offer %}

              <div class="showcase-container">

                <div class="showcase">
                  
                  <div class="showcase-banner">
                      <a href="{% url 'products:detail' offer.product.handle %}">
                    <img src="{{ offer.product.image.url }}" alt="{{ offer.product.name }}" class="showcase-img">
                      </a>
                  </div>

                  <div class="showcase-content">
                    
                   <div class="showcase-rating">
                          {% for i in "12345"|make_list %}
                              {% with j=i|add:-1 %}

                              {% if i|add:0  <= offer.product.rating_product.average_rating %}
                        <ion-icon name="star"></ion-icon>



                              {% endif %}

                              {% if i|add:0  > offer.product.rating_product.average_rating and j|add:0  < offer.product.rating_product.average_rating  %}
                                      <ion-icon name="star-half"></ion-icon>  <!-- Estrella media -->
                        {% else %}

                                      {% endif %}

                             {% if i|add:0  >= offer.product.rating_product.average_rating and j|add:0  >= offer.product.rating_product.average_rating %}
                              <ion-icon name="star-outline"></ion-icon>
                                  {% endif %}
{% endwith %}
                              {% endfor %}


                      </div>

                    <a href="{% url 'products:detail' offer.product.handle %}">
                      <h3 class="showcase-title">{{ offer.product.name }}</h3>
                    </a>

                  {% if offer.product.short_description %}
                    <p class="showcase-desc">
                      {{ offer.product.short_description }}
                    </p>
                  {% endif %}

                    <div class="price-box">
                      <p class="price">{{ offer.product.price }} cup</p>

                      <del>{{ offer.precio_viejo }} cup</del>
                    </div>
<form id="add-to-cart-form2" onsubmit="event.preventDefault(); addToCart({{ offer.product.id }}, 1);">
      {% csrf_token %}
                    <button type="submit" class="add-cart-btn">Agregar al carro</button>
 </form>

                    <div class="showcase-status">
                      <div class="wrapper">
{#                        <p>#}
{#                          already sold: <b>20</b>#}
{#                        </p>#}

                        <p>
                          Disponibles: <b>{{ offer.product.supply }}</b>
                        </p>
                      </div>

{#                      <div class="showcase-status-bar"></div>#}
                    </div>

                    <div class="countdown-box">

                      <p class="countdown-desc">
                        Rapido! la oferta termina en:
                      </p>

                      <div class="countdown">
    {% if offer.get_time_remaining == "Oferta sin fecha de finalización definida" or offer.get_time_remaining.minutes == None %}
        <p class="no-end-date-text">Esta oferta puede terminar en cualquier momento</p>
    {% else %}

        <div class="countdown-content">
            <p class="display-number">{{ offer.get_time_remaining.days }}</p>
            <p class="display-text">Days</p>
        </div>
        <div class="countdown-content">
            <p class="display-number">{{ offer.get_time_remaining.hours }}</p>
            <p class="display-text">Hours</p>
        </div>
        <div class="countdown-content">
            <p class="display-number">{{ offer.get_time_remaining.minutes }}</p>
            <p class="display-text">Min</p>
        </div>
    {% endif %}
</div>

                    </div>

                  </div>

                </div>

              </div>

                {% endfor %}


            </div>

          </div>

<style>
    .no-end-date-text {
    background-color: #ffc107; /* Color de fondo amarillo */
    color: #333; /* Color del texto oscuro */
    padding: 10px; /* Espaciado interno */
    border-radius: 5px; /* Bordes redondeados */
    font-weight: bold; /* Texto en negrita */
    text-align: center; /* Alineación centrada */
}




#carousel {
  display: flex;
  overflow: hidden;
  scroll-behavior: smooth;
  position: relative;
}

.showcase-container {
  min-width: 100%; /* Cada elemento ocupa todo el ancho del contenedor */
  transition: transform 0.5s ease-in-out;
}

</style>

<script>
 document.addEventListener("DOMContentLoaded", () => {
  const carousel = document.getElementById("carousel");
  let scrollAmount = 0;
  const scrollStep = 300; // Cantidad de desplazamiento en píxeles
  const scrollInterval = 3000; // Intervalo de tiempo en milisegundos

  function autoScroll() {
    scrollAmount += scrollStep;
    if (scrollAmount >= carousel.scrollWidth) {
      scrollAmount = 0; // Reinicia el scroll al inicio
    }
    carousel.scrollTo({
      left: scrollAmount,
      behavior: "smooth",
    });
  }

  // Configura el intervalo
  setInterval(autoScroll, scrollInterval);
});

</script>

templates/products/productosMinimal.html
<div class="product-box">

    <!--
      - PRODUCT MINIMAL
    -->

<style>
  html {
  scroll-behavior: smooth;
}

</style>


    <div class="product-minimal">

        {% if new_products %}
      <div class="product-showcase">

        {% if no_nuevos == False %}
        <h2 class="title">Nuevos</h2>
            {% else %}
            <h2 class="title">Más like</h2>
            {% endif %}

        <div class="showcase-wrapper  has-scrollbar ">

          <div class="showcase-container">
       {% for product in new_products %}
            <div class="showcase">

              <a href="{% url 'products:detail' product.handle %}" class="showcase-img-box">

                   <img src=" {% if product.image %}  {{ product.image.url }}"   {% endif %} alt="{{ product.name }}" width="70" class="showcase-img">

              </a>

              <div class="showcase-content">

                <a href="{% url 'products:detail' product.handle %}">
                  <h4 class="showcase-title">{{ product.name}}</h4>
                </a>

                {% if product.category %}

                <a href="{% url 'products:list' %}?category={{ product.category.pk }}" class="showcase-category">{{ product.category }}</a>

                   {% endif %}


                <div class="price-box">

                  <p class="price">{{ product.price }} cup</p>

                </div>

              </div>

            </div>
              {% endfor %}

          </div>



        </div>

      </div>
        {% endif %}

      <div class="product-showcase">

        <h2 class="title">Tendencia</h2>

        <div class="showcase-wrapper  has-scrollbar">

          <div class="showcase-container">

            {% for product in trending_products %}

            <div class="showcase">

              <a href="{% url 'products:detail' product.handle %}" class="showcase-img-box">
                <img src=" {% if product.image %}{{ product.image.url }} {% endif %}" alt="{{ product.name }}" class="showcase-img"
                  width="70">
              </a>

              <div class="showcase-content">

                <a href="{% url 'products:detail' product.handle %}">
                  <h4 class="showcase-title">{{ product.name }}</h4>
                </a>

               {% if product.category %}

                <a href="{% url 'products:list' %}?category={{ product.category.pk }}" class="showcase-category">{{ product.category }}</a>

                   {% endif %}

                <div class="price-box">

                  <p class="price">{{ product.price }} cup</p>

                </div>

              </div>

            </div>

          {% endfor %}




          </div>


        </div>

      </div>

      <div class="product-showcase">

        <h2 class="title">Mejor Calificación</h2>

        <div class="showcase-wrapper  has-scrollbar">

          <div class="showcase-container">

              {% for product in top_rated %}

            <div class="showcase">

              <a href="{% url 'products:detail' product.handle %}" class="showcase-img-box">
                <img src=" {% if product.image %}{{ product.image.url }} {% endif %}" alt="{{ product.name }}" class="showcase-img"
                  width="70">
              </a>

              <div class="showcase-content">

                <a href="{% url 'products:detail' product.handle %}">
                  <h4 class="showcase-title">{{ product.name }}</h4>
                </a>

               {% if product.category %}

                <a href="{% url 'products:list' %}?category={{ product.category.pk }}" class="showcase-category">{{ product.category }}</a>

                   {% endif %}

                <div class="price-box">

                  <p class="price">{{ product.price }} cup</p>

                </div>

              </div>

            </div>

              {% endfor %}



          </div>



        </div>

      </div>

    </div>

    <script>
    document.addEventListener("DOMContentLoaded", () => {
  const showcases = document.querySelectorAll(".product-showcase");

  showcases.forEach((showcase, index) => {
    const container = showcase.querySelector(".showcase-wrapper");

    if (container) {
      container.addEventListener("scroll", () => {
        // Calcular si el usuario ha llegado al final del scroll
        const isAtEnd =
          Math.ceil(container.scrollLeft + container.clientWidth) >= container.scrollWidth;

        if (isAtEnd && showcases[index + 1]) {
          // Mover al siguiente showcase si existe
          showcases[index + 1].scrollIntoView({ behavior: "smooth" });
        }
      });
    }
  });
});


    </script>