carro/urls.py
from django.urls import path

from . import views

app_name = 'carro'
urlpatterns = [
    path('agregar/<int:product_id>/', views.agregar_producto, name='agregar'),
    path('agregar_cantidad/<int:product_id>/<int:quantity>/', views.agregar_producto_cantidad, name='agregar_cantidad'),
    path('agregar_carro/<int:product_id>/', views.agregar_producto_desde_carro, name='agregar_carro'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:product_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    path('carro/', views.ver_carro, name='ver_carro'),

    path('contar/', views.contar_carro, name='contar_carro'),



]

micro_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuario.views import MyPasswordChangeView
from . import views

urlpatterns = [

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='usuario/reset_pass/password_reset.html'), name='password_reset'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='usuario/reset_pass/complete.html'), name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='usuario/reset_pass/confirm.html'), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='usuario/reset_pass/done.html'), name='password_reset_done'),

    path('administrador/', admin.site.urls, name='admin'),
    path('', include('products.urls')),
    path('carro/', include('carro.urls')),
    path('usuario/', include('usuario.urls')),
    path('extra/', include('extra.urls')),
    path('ventas/', include('ventas.urls')),
    path('pedidos/', include('pedidos_stripe.urls')),



    path('<int:user_id>/password/', MyPasswordChangeView.as_view(),
             name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

purchases/urls.py
from django.urls import path

from . import views

app_name='purchases'
urlpatterns = [


    # COmpra con zelle
    # path('create_solicitud/', views.create_solicitud, name='create_solicitud'),
    path('ver_solicitud/<int:id_solicitud>', views.view_solicitud_zelle, name='ver_solicitud'),
    path('list_solicitud/', views.solicitud_list, name='solicitud_list'),
    path('aceptar_solicitud/<int:id_solicitud>', views.aceptar_solicitud, name='aceptar_solicitud'),
    path('cancelar_solicitud/<int:id_solicitud>', views.cancelar_solicitud, name='cancelar_solicitud'),
    path('success_cart/', views.purchase_success_cart_view, name='success_cart'),
]

purchases/models.py
# Create your models here.


from django.db import models
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from carro.carro import Carro
from products.models import Product
from django.core.exceptions import PermissionDenied
from django.core.validators import EmailValidator,RegexValidator

from django.db import models
from django.conf import settings
from django.core.validators import EmailValidator, RegexValidator
# Create your models here.



class SolicitudZelle(models.Model):
    STATUS_CHOICES = [
        ('pending', 'En espera'),
        ('accepted', 'Aceptada'),
        ('canceled', 'Cancelada'),
    ]
    ENTREGA_CHOICES = [
        ('pending', 'En espera'),
        ('onway', 'En camino'),
        ('accepted', 'Entregada'),
        ('canceled', 'Cancelada'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    products = models.ManyToManyField(Product, related_name='purchases')
    email = models.EmailField(validators=[EmailValidator])
    file = models.FileField(upload_to='purchase_files')
    phone = models.CharField(max_length=15, validators=[RegexValidator(regex=r'^\+?1?\d{9,15}$')])
    payment_verification_code = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Campo para la cantidad de dinero
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')  # Campo para el estado de la solicitud
    entrega = models.CharField(max_length=10, choices=ENTREGA_CHOICES, default='pending')  # Campo para el estado de la solicitud

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.pk} - {self.user.username}"


    def guardar_producto(self,product,quantity,solicitud):

        SolicitudZelleItem.objects.create(
            solicitud=solicitud,
            product=product,
            quantity=quantity
        )

    def accept(self):
        for product in self.products.all():
            object = get_object_or_404(Product, pk=product.pk)
            solicitud_items = SolicitudZelleItem.objects.filter(solicitud=self,product=product)

            try:
                for solicitud_item in solicitud_items:
                    object.supply = object.supply - solicitud_item.quantity
                object.save()
            except:
                return HttpResponse("No hay sufuciente productos para esta solicitud")

        self.status = 'accepted'
        self.save()


    def cancel(self):
        self.status = 'canceled'
        self.save()



class SolicitudZelleItem(models.Model):
    solicitud = models.ForeignKey(SolicitudZelle, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        self.total_price = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"id:{self.pk} - Products:{self.product.name} - {self.quantity}"

purchases/views.py
# Create your views here.
import random
import stripe
from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from carro.carro import Carro
from extra.models import Destinatario
from products.models import Product
from usuario.decorator import role_required
from .form import SolicitudZelleForm
from .models import Solicitud, SolicitudItem


from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags





def buy_cart_solicitud(request,destinatario_id):
    if not request.user.is_authenticated:
        messages.warning(request, 'Debes estar registrado para poder realizar compras.')
        return HttpResponseRedirect(reverse('usuario:login'))



    if request.method == 'POST':
        destinatario = get_object_or_404(Destinatario, pk=destinatario_id)



    total = 0
    if not request.method == "POST":
        return HttpResponseBadRequest()

    purchase = Solicitud.objects.create(user=request.user)
    request.session['purchase_id'] = purchase.id
    if destinatario:
        if destinatario.nombre:
            purchase.nombre = destinatario.nombre
        if destinatario.apellidos:
            purchase.apellidos = destinatario.apellidos
        if destinatario.telefono:
            purchase.telefono = destinatario.telefono
        if destinatario.carnet_de_identidad:
            purchase.carnet_de_identidad = destinatario.carnet_de_identidad
        if destinatario.correo_electronico:
            purchase.correo_electronico = destinatario.correo_electronico
        if destinatario.direccion:
            purchase.direccion = destinatario.direccion
        if destinatario.municipio:
            purchase.municipio = destinatario.municipio
        if destinatario.instrucciones_entrega:
            purchase.instrucciones_entrega = destinatario.instrucciones_entrega


    session = request.session
    carro = session.get('carro', {})

    if not carro:
        return HttpResponseBadRequest("El carrito está vacío.")

    cart_items = carro.items()
    stock_error_products = []
    line_items = []
    for item_id, item in cart_items:
        product = get_object_or_404(Product, pk=item["product_id"])
        line_items.append({
            "price": product.price,
            "quantity": item["cantidad"],
        })
        if product.supply < item["cantidad"]:
            stock_error_products.append(product.name)

    if stock_error_products:
        stock_error = "Lo sentimos, no hay suficiente disponibilidad de los siguientes productos: " + ", ".join(
            stock_error_products) + ". Te recomendamos que los retires del carrito para continuar con tu compra."
        context = {
            "stock_error": stock_error
        }
        return render(request, "purchases/cart.html", context)
    else:
        stock_error = None




    for item_id, item in cart_items:
        product = get_object_or_404(Product, pk=item["product_id"])
        purchase.product.add(product)
        purchase.guardar_producto(product=product, quantity=item["cantidad"], purchase=purchase)
        total = total + item["subtotal"]

    purchase.stripe_price = total
    purchase.save()


    return redirect('purchases:success_cart')



@login_required
def view_solicitud_zelle(request, id_solicitud):
    solicitud = get_object_or_404(Solicitud, id=id_solicitud)

    # Check if the user has permission to view the solicitud
    if request.user != solicitud.user and request.user.usuario.rol.nombre != 'admin':
        return render(request, 'error.html', {'error_message': 'No tienes permiso para ver esta solicitud.'}, status=403)

    # Get the SolicitudZelleItem objects associated with the solicitud

    solicitud_items = SolicitudItem.objects.filter(solicitud=solicitud)



    context = {
        'solicitud': solicitud,
        'solicitud_items': solicitud_items,
    }

    return render(request, 'purchases/ver_solicitud_zelle.html', context)



@login_required
def solicitud_list(request):
    # Obtener los parámetros de filtro de la solicitud

    filter_usuario = request.GET.get('usuario' or None)

    if request.user.usuario.rol.nombre == 'admin':



        # Filtrar las solicitudes en base a los parámetros
        if filter_usuario:
            solicitudes = Solicitud.objects.filter(user__username__icontains=filter_usuario)
        else:
            solicitudes = Solicitud.objects.all()
    else:
        solicitudes = Solicitud.objects.filter(user=request.user)



    filter_estado = request.GET.get('estado')
    if filter_estado:
        solicitudes = solicitudes.filter(status=filter_estado)
    else:
        solicitudes = solicitudes.order_by('-status', '-id')

    # Paginar las solicitudes
    page_size = 20  # Número de solicitudes por página
    paginator = Paginator(solicitudes, page_size)
    page_number = request.GET.get('page', 1)

    try:
        page_solicitudes = paginator.page(page_number)
    except PageNotAnInteger:
        page_solicitudes = paginator.page(1)
    except EmptyPage:
        page_solicitudes = paginator.page(paginator.num_pages)



    context = {
        'solicitudes': page_solicitudes,
        'filter_usuario': filter_usuario,
        'filter_estado': filter_estado
    }
    return render(request, 'purchases/solicitud_list.html', context)


@role_required(['admin'])
def aceptar_solicitud(request,id_solicitud):
    solicitud = get_object_or_404(Solicitud, id=id_solicitud)
    solicitud.accept()
    print("se acepto la solicitud")

    context = {
        "id": id_solicitud,
    }
    html_message = render_to_string('purchases/email/solicitud_aceptada.html', context)
    plain_message = strip_tags(html_message)
    subject_email = "Solicitud de compra con E-commerce aceptada con éxito"
    user_email = solicitud.correo_electronico

    send_mail(
        subject=subject_email,
        message=plain_message,
        from_email=EMAIL_HOST_USER,
        recipient_list=[user_email],
        html_message=html_message,
        fail_silently=False,
    )
    print("se mando el email")
    return redirect('purchases:solicitud_list')


@role_required(['admin'])
def cancelar_solicitud(request,id_solicitud):
    solicitud = get_object_or_404(Solicitud, id=id_solicitud)

    context = {
        "id": id_solicitud,
    }
    html_message = render_to_string('purchases/email/solicitud_rechazada.html', context)
    plain_message = strip_tags(html_message)
    subject_email = "Solicitud de compra con E-commerce rechazada"
    user_email = solicitud.email

    send_mail(
        subject=subject_email,
        message=plain_message,
        from_email=EMAIL_HOST_USER,
        recipient_list=[user_email],
        html_message=html_message,
        fail_silently=False,
    )

    solicitud.cancel()
    return redirect('purchases:solicitud_list')



# def buy_cart(request,destinatario_id):
#     if not request.user.is_authenticated:
#         messages.warning(request, 'Debes estar registrado para poder realizar compras.')
#         return HttpResponseRedirect(reverse('usuario:login'))
#
#     if request.method == 'POST':
#         destinatario = get_object_or_404(Destinatario, pk=destinatario_id)
#
#     total = 0
#     if not request.method == "POST":
#         return HttpResponseBadRequest()
#
#     purchase = Solicitud.objects.create(user=request.user)
#     request.session['purchase_id'] = purchase.id
#     if destinatario:
#         if destinatario.nombre:
#             purchase.nombre = destinatario.nombre
#         if destinatario.apellidos:
#             purchase.apellidos = destinatario.apellidos
#         if destinatario.telefono:
#             purchase.telefono = destinatario.telefono
#         if destinatario.carnet_de_identidad:
#             purchase.carnet_de_identidad = destinatario.carnet_de_identidad
#         if destinatario.correo_electronico:
#             purchase.correo_electronico = destinatario.correo_electronico
#         if destinatario.direccion:
#             purchase.direccion = destinatario.direccion
#         if destinatario.municipio:
#             purchase.municipio = destinatario.municipio
#         if destinatario.instrucciones_entrega:
#             purchase.instrucciones_entrega = destinatario.instrucciones_entrega
#
#
#     session = request.session
#     carro = session.get('carro', {})
#
#     if not carro:
#         return HttpResponseBadRequest("El carrito está vacío.")
#
#     cart_items = carro.items()
#     stock_error_products = []
#     line_items = []
#
#     for item_id, item in cart_items:
#         product = get_object_or_404(Product, pk=item["product_id"])
#         purchase.product.add(product)
#         purchase.guardar_producto(product=product, quantity=item["cantidad"], purchase=purchase)
#         total = total + item["subtotal"]
#
#     purchase.stripe_price = total
#     purchase.save()
#
#     return redirect('solicitud_list')



def purchase_success_cart_view(request):
    purchase_id = request.session.get("purchase_id")
    session = request.session
    carro = session.get('carro', {})
    cart_items = carro.items()


    for item_id, item in cart_items:
        product = get_object_or_404(Product, pk=item["product_id"])
        product.supply = product.supply - item["cantidad"]
        product.save()


    carro = Carro(request)
    carro.limpiar_carro()

    if purchase_id:
        purchase = Solicitud.objects.get(id=int(purchase_id))
        purchase.completed = True
        purchase.save()
        del request.session['purchase_id']

        # Enviar email al usuario si tiene

templates/purchases/zelle/crear_solicitud_zelle.html
{% extends "../base.html" %}

{% block content %}
{% load static %}


    <div class="bg-white shadow-md rounded-lg p-8 w-full max-w-md">
        <h1 class="text-2xl font-bold mb-4">Create Solicitud Zelle</h1>
        <form method="post" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            {% for field in form %}
            <div>
                <label for="{{ field.id_for_label }}" class="block font-medium text-gray-700 mb-2">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                <p class="text-red-500 text-sm mt-1">{{ field.errors.0 }}</p>
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">Submit</button>
        </form>
    </div>


<div class="w-full lg:w-3/4">
        {% include 'purchases/cart-table.html' %}
      </div>


    <div class="flex justify-between font-bold text-gray-900 dark:text-white mb-2">
            Total: <span>${{ importe_total_carro }}</span>
          </div>

{% endblock %}

templates/purchases/zelle/tabla_zelle.html
<div class="container mx-auto my-8">
    <h1 class="text-2xl font-bold mb-4">Listado de Solicitudes Zelle</h1>
    <div class="overflow-x-auto">
        <table class="w-full table-auto">
            <thead>
                <tr class="bg-gray-200">
                    <th class="px-4 py-2">Usuario</th>
                    <th class="px-4 py-2">Email</th>
                    <th class="px-4 py-2">Teléfono</th>
                    <th class="px-4 py-2">Codigo</th>
                    <th class="px-4 py-2">Monto</th>
                    <th class="px-4 py-2">Estado</th>
                    <th class="px-4 py-2">Entrega</th>
                    <th class="px-4 py-2">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for solicitud in solicitudes %}
                <tr class="border-b">
                    <td class="px-4 py-2"><a href="{% url 'purchases:ver_solicitud' solicitud.id %}" >{{ solicitud.user.username }} </a></td>
                    <td class="px-4 py-2"> <a href="{% url 'purchases:ver_solicitud' solicitud.id %}">{{ solicitud.email }} </a></td>
                    <td class="px-4 py-2"> <a href="{% url 'purchases:ver_solicitud' solicitud.id %}" >{{ solicitud.phone }} </a></td>
                    <td class="px-4 py-2"> <a href="{% url 'purchases:ver_solicitud' solicitud.id %}" >{{ solicitud.payment_verification_code }} </a></td>
                    <td class="px-4 py-2"> <a href="{% url 'purchases:ver_solicitud' solicitud.id %}" >{{ solicitud.amount }} </a></td>
                    <td class="px-4 py-2"> <a href="{% url 'purchases:ver_solicitud' solicitud.id %}">{{ solicitud.get_status_display }} </a></td>

                    <td class="px-4 py-2"> {% if solicitud.status == 'accepted' %}{{ solicitud.get_entrega_display }} {% endif %}</td>

                   <td class="my-custom-class">

      {% if request.user.usuario.rol.nombre == 'admin' %}

  <div class="flex gap-2">
  {% if solicitud.status == 'pending'  %}
    <a href="{% url 'purchases:aceptar_solicitud' id_solicitud=solicitud.pk %}" >Aceptar</a>
    <a href="{% url 'purchases:cancelar_solicitud' id_solicitud=solicitud.pk %}" >Cancelar</a>
  </div>
            {% endif %}
  {% endif %}

</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="mt-4 flex justify-center">
        <div class="btn-group">
            {% if solicitudes.has_previous %}
            <a href="?page=1" class="btn">Primero</a>
            <a href="?page={{ solicitudes.previous_page_number }}" class="btn">Anterior</a>
            {% endif %}

            <span class="btn disabled">Página {{ solicitudes.number }} de {{ solicitudes.paginator.num_pages }}</span>

            {% if solicitudes.has_next %}
            <a href="?page={{ solicitudes.next_page_number }}" class="btn">Siguiente</a>
            <a href="?page={{ solicitudes.paginator.num_pages }}" class="btn">Último</a>
            {% endif %}
        </div>
    </div>
</div>

    <style>


.my-custom-class {
  padding-left: 1rem;
  padding-right: 1rem;
  padding-top: 0.5rem;
  padding-bottom: 0.5rem;
}

.my-custom-class .flex {
  display: flex;
  gap: 0.5rem;
}

.my-custom-class .flex a {
  display: inline-block;
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  background-color: #6b7280;
  color: #fff;
  text-decoration: none;
  transition: background-color 0.3s ease;
}

.my-custom-class .flex a:hover {
  background-color: #4b5563;
}

.my-custom-class .flex a.bg-green-500 {
  background-color: #16a34a;
}

.my-custom-class .flex a.bg-green-500:hover {
  background-color: #15803d;
}

.my-custom-class .flex a.bg-red-500 {
  background-color: #dc2626;
}

.my-custom-class .flex a.bg-red-500:hover {
  background-color: #b91c1c;
}

.my-custom-class a {
  display: inline-block;
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  background-color: #6b7280;
  color: #fff;
  text-decoration: none;
  transition: background-color 0.3s ease;
}

.my-custom-class a:hover {
  background-color: #4b5563;
}



</style>

templates/purchases/zelle/ver_solicitud_zelle.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-2xl font-bold mb-4">Detalles de la Solicitud de Zelle</h1>

    <div class="bg-white shadow-md rounded-lg overflow-hidden">
        <div class="px-6 py-4">
            <h2 class="text-lg font-medium mb-2">Solicitante: {{ solicitud.user.username }}</h2>
            <div class="text-gray-700 leading-relaxed">
                <p class="mb-2"><strong>Estado:</strong> {{ solicitud.get_status_display }}</p>
            {% if solicitud.status == 'accepted' %}
                <p class="mb-2"><strong>Estado:</strong> {{ solicitud.get_entrega_display }}</p>
            {% endif %}
                <p class="mb-2"><strong>Correo electrónico:</strong> {{ solicitud.email }}</p>
                <p class="mb-2"><strong>Teléfono:</strong> {{ solicitud.phone }}</p>
                <p class="mb-2"><strong>Monto:</strong> ${{ solicitud.amount }}</p>
                <p class="mb-2"><strong>Código de verificación de pago:</strong> {{ solicitud.payment_verification_code }}</p>
                <p class="mb-2"><strong>Archivo:</strong> {% if solicitud.file %}<a href="{{ solicitud.file.url }}" class="text-blue-500 hover:text-blue-700">Ver archivo</a>{% else %}No se ha cargado ningún archivo{% endif %}</p>
                <p class="mb-2"><strong>Fecha de creación:</strong> {{ solicitud.created_at }}</p>
                <p class="mb-2"><strong>Última actualización:</strong> {{ solicitud.updated_at }}</p>
            </div>
        </div>
    </div>

    <h2 class="text-xl font-bold mt-8 mb-4">Productos</h2>
    {% if solicitud.products.all %}
    <div class="bg-white shadow-md rounded-lg overflow-hidden">
        <div class="px-6 py-4">
            <table class="w-full">
                <thead>
                    <tr class="bg-gray-200">
                        <th class="py-2 px-4 text-left">Nombre</th>
                        <th class="py-2 px-4 text-left">Precio</th>
                        <th class="py-2 px-4 text-left">Cantidad</th>
                        <th class="py-2 px-4 text-left">SubTotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in solicitud_items  %}
                    <tr class="border-b">
                        <td class="py-2 px-4">{{ item.product.name }}</td>
                        <td class="py-2 px-4">${{ item.product.price }}</td>
                        <td class="py-2 px-4">{{ item.quantity  }}</td>
                        <td class="py-2 px-4">${{ item.total_price }}  </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <p class="text-gray-700">No se han encontrado productos asociados a esta solicitud.</p>
    {% endif %}

<style>
  .admin-actions {
    margin-top: 2rem;
    display: flex;
    justify-content: flex-end;
  }

  .admin-actions a {
    background-color: #007bff;
    color: #fff;
    padding: 0.5rem 1rem;
    text-decoration: none;
    border-radius: 0.25rem;
    margin-left: 0.5rem;
  }

  .admin-actions a:hover {
    background-color: #0056b3;
  }
</style>

{% if request.user.usuario.rol.nombre == 'admin' %}

  <div class="admin-actions">
  {% if solicitud.status == 'canceled' %}
    <a href="{% url 'purchases:aceptar_solicitud' solicitud.id %}">
      Aceptar solicitud
    </a>
      {% endif %}
   {% if solicitud.status == 'accepted' %}
    <a href="{% url 'purchases:cancelar_solicitud' solicitud.id %}">
      Cancelar solicitud
    </a>
       {% endif %}
  </div>
{% endif %}
</div>
{% endblock %}