carro/urls.py
from django.urls import path

from . import views

app_name = 'carro'
urlpatterns = [
    path('agregar/<int:product_id>/', views.agregar_producto, name='agregar'),
    path('agregar_cantidad/<int:product_id>/<int:quantity>/', views.agregar_producto_cantidad, name='agregar_cantidad'),
    path('agregar_carro/<int:product_id>/', views.agregar_producto_desde_carro, name='agregar_carro'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:product_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    path('carro/', views.ver_carro, name='ver_carro'),

    path('contar/', views.contar_carro, name='contar_carro'),



]

extra/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

app_name='extra'
urlpatterns = [

    path('crear_destinatario/', views.crear_destinatario , name='crear_destinatario'),
    path('list_destinatario/', views.lista_destinatarios , name='list_destinatario'),
    path('editar_destinatario/<int:destinatario_id>', views.editar_destinatario , name='editar_destinatario'),
    path('eliminar_destinatario/<int:destinatario_id>', views.eliminar_destinatario , name='eliminar_destinatario'),


]

micro_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuario.views import MyPasswordChangeView
from . import views

urlpatterns = [

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='usuario/reset_pass/password_reset.html'), name='password_reset'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='usuario/reset_pass/complete.html'), name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='usuario/reset_pass/confirm.html'), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='usuario/reset_pass/done.html'), name='password_reset_done'),

    path('administrador/', admin.site.urls, name='admin'),
    path('', include('products.urls')),
    path('carro/', include('carro.urls')),
    path('usuario/', include('usuario.urls')),
    path('extra/', include('extra.urls')),
    path('ventas/', include('ventas.urls')),
    path('pedidos/', include('pedidos_stripe.urls')),



    path('<int:user_id>/password/', MyPasswordChangeView.as_view(),
             name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [

    path('get_hijas/', views.get_hijas, name='get_hijas'),

    path('create/', views.product_create_view, name='create'),
    path('mis_productos_table/', views.mis_productos_table, name='mis_productos'),
    path('', views.product_list_view, name='list'),
    path('filter/<int:provider_id>/', views.product_list_view, name='filter_by_provider'),
    path('like_filter/<int:provider_id>/', views.product_list_view, name='filter_by_provider'),
    path('promotion/<int:promotion_id>/', views.product_list_view, name='promotion'),



    path('<slug:handle>/', views.product_detail_view, name='detail'),
    path('<slug:handle>/manage/', views.product_manage_detail_view, name='manage'),
    path('<slug:handle>/download/<int:pk>', views.product_attachment_download_view, name='download'),

    path('search/', views.search, name='search'),

    # path('eliminar/<slug:handle>/', views.delete_product, name='eliminar'),


    #Crear oferta
    path('crear_oferta/<int:product_id>/', views.crear_oferta, name='crear_oferta'),
    path('eliminar_oferta/<int:product_id>/', views.eliminar_oferta, name='eliminar_oferta'),
    path('rate_product/<int:product_id>/', views.rate_product, name='rate_product'),

    path('like_product/<int:product_id>/', views.like_product, name='like'),
    path('dislike_product/<int:product_id>/', views.dislike_product, name='dislike'),




]

purchases/urls.py
from django.urls import path

from . import views

app_name='purchases'
urlpatterns = [


    # COmpra con zelle
    # path('create_solicitud/', views.create_solicitud, name='create_solicitud'),
    path('ver_solicitud/<int:id_solicitud>', views.view_solicitud_zelle, name='ver_solicitud'),
    path('list_solicitud/', views.solicitud_list, name='solicitud_list'),
    path('aceptar_solicitud/<int:id_solicitud>', views.aceptar_solicitud, name='aceptar_solicitud'),
    path('cancelar_solicitud/<int:id_solicitud>', views.cancelar_solicitud, name='cancelar_solicitud'),
    path('success_cart/', views.purchase_success_cart_view, name='success_cart'),
]

purchases/views.py
# Create your views here.
import random
import stripe
from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from carro.carro import Carro
from extra.models import Destinatario
from products.models import Product
from usuario.decorator import role_required
from .form import SolicitudZelleForm
from .models import Solicitud, SolicitudItem


from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags





def buy_cart_solicitud(request,destinatario_id):
    if not request.user.is_authenticated:
        messages.warning(request, 'Debes estar registrado para poder realizar compras.')
        return HttpResponseRedirect(reverse('usuario:login'))



    if request.method == 'POST':
        destinatario = get_object_or_404(Destinatario, pk=destinatario_id)



    total = 0
    if not request.method == "POST":
        return HttpResponseBadRequest()

    purchase = Solicitud.objects.create(user=request.user)
    request.session['purchase_id'] = purchase.id
    if destinatario:
        if destinatario.nombre:
            purchase.nombre = destinatario.nombre
        if destinatario.apellidos:
            purchase.apellidos = destinatario.apellidos
        if destinatario.telefono:
            purchase.telefono = destinatario.telefono
        if destinatario.carnet_de_identidad:
            purchase.carnet_de_identidad = destinatario.carnet_de_identidad
        if destinatario.correo_electronico:
            purchase.correo_electronico = destinatario.correo_electronico
        if destinatario.direccion:
            purchase.direccion = destinatario.direccion
        if destinatario.municipio:
            purchase.municipio = destinatario.municipio
        if destinatario.instrucciones_entrega:
            purchase.instrucciones_entrega = destinatario.instrucciones_entrega


    session = request.session
    carro = session.get('carro', {})

    if not carro:
        return HttpResponseBadRequest("El carrito está vacío.")

    cart_items = carro.items()
    stock_error_products = []
    line_items = []
    for item_id, item in cart_items:
        product = get_object_or_404(Product, pk=item["product_id"])
        line_items.append({
            "price": product.price,
            "quantity": item["cantidad"],
        })
        if product.supply < item["cantidad"]:
            stock_error_products.append(product.name)

    if stock_error_products:
        stock_error = "Lo sentimos, no hay suficiente disponibilidad de los siguientes productos: " + ", ".join(
            stock_error_products) + ". Te recomendamos que los retires del carrito para continuar con tu compra."
        context = {
            "stock_error": stock_error
        }
        return render(request, "purchases/cart.html", context)
    else:
        stock_error = None




    for item_id, item in cart_items:
        product = get_object_or_404(Product, pk=item["product_id"])
        purchase.product.add(product)
        purchase.guardar_producto(product=product, quantity=item["cantidad"], purchase=purchase)
        total = total + item["subtotal"]

    purchase.stripe_price = total
    purchase.save()


    return redirect('purchases:success_cart')



@login_required
def view_solicitud_zelle(request, id_solicitud):
    solicitud = get_object_or_404(Solicitud, id=id_solicitud)

    # Check if the user has permission to view the solicitud
    if request.user != solicitud.user and request.user.usuario.rol.nombre != 'admin':
        return render(request, 'error.html', {'error_message': 'No tienes permiso para ver esta solicitud.'}, status=403)

    # Get the SolicitudZelleItem objects associated with the solicitud

    solicitud_items = SolicitudItem.objects.filter(solicitud=solicitud)



    context = {
        'solicitud': solicitud,
        'solicitud_items': solicitud_items,
    }

    return render(request, 'purchases/ver_solicitud_zelle.html', context)



@login_required
def solicitud_list(request):
    # Obtener los parámetros de filtro de la solicitud

    filter_usuario = request.GET.get('usuario' or None)

    if request.user.usuario.rol.nombre == 'admin':



        # Filtrar las solicitudes en base a los parámetros
        if filter_usuario:
            solicitudes = Solicitud.objects.filter(user__username__icontains=filter_usuario)
        else:
            solicitudes = Solicitud.objects.all()
    else:
        solicitudes = Solicitud.objects.filter(user=request.user)



    filter_estado = request.GET.get('estado')
    if filter_estado:
        solicitudes = solicitudes.filter(status=filter_estado)
    else:
        solicitudes = solicitudes.order_by('-status', '-id')

    # Paginar las solicitudes
    page_size = 20  # Número de solicitudes por página
    paginator = Paginator(solicitudes, page_size)
    page_number = request.GET.get('page', 1)

    try:
        page_solicitudes = paginator.page(page_number)
    except PageNotAnInteger:
        page_solicitudes = paginator.page(1)
    except EmptyPage:
        page_solicitudes = paginator.page(paginator.num_pages)



    context = {
        'solicitudes': page_solicitudes,
        'filter_usuario': filter_usuario,
        'filter_estado': filter_estado
    }
    return render(request, 'purchases/solicitud_list.html', context)


@role_required(['admin'])
def aceptar_solicitud(request,id_solicitud):
    solicitud = get_object_or_404(Solicitud, id=id_solicitud)
    solicitud.accept()
    print("se acepto la solicitud")

    context = {
        "id": id_solicitud,
    }
    html_message = render_to_string('purchases/email/solicitud_aceptada.html', context)
    plain_message = strip_tags(html_message)
    subject_email = "Solicitud de compra con E-commerce aceptada con éxito"
    user_email = solicitud.correo_electronico

    send_mail(
        subject=subject_email,
        message=plain_message,
        from_email=EMAIL_HOST_USER,
        recipient_list=[user_email],
        html_message=html_message,
        fail_silently=False,
    )
    print("se mando el email")
    return redirect('purchases:solicitud_list')


@role_required(['admin'])
def cancelar_solicitud(request,id_solicitud):
    solicitud = get_object_or_404(Solicitud, id=id_solicitud)

    context = {
        "id": id_solicitud,
    }
    html_message = render_to_string('purchases/email/solicitud_rechazada.html', context)
    plain_message = strip_tags(html_message)
    subject_email = "Solicitud de compra con E-commerce rechazada"
    user_email = solicitud.email

    send_mail(
        subject=subject_email,
        message=plain_message,
        from_email=EMAIL_HOST_USER,
        recipient_list=[user_email],
        html_message=html_message,
        fail_silently=False,
    )

    solicitud.cancel()
    return redirect('purchases:solicitud_list')



# def buy_cart(request,destinatario_id):
#     if not request.user.is_authenticated:
#         messages.warning(request, 'Debes estar registrado para poder realizar compras.')
#         return HttpResponseRedirect(reverse('usuario:login'))
#
#     if request.method == 'POST':
#         destinatario = get_object_or_404(Destinatario, pk=destinatario_id)
#
#     total = 0
#     if not request.method == "POST":
#         return HttpResponseBadRequest()
#
#     purchase = Solicitud.objects.create(user=request.user)
#     request.session['purchase_id'] = purchase.id
#     if destinatario:
#         if destinatario.nombre:
#             purchase.nombre = destinatario.nombre
#         if destinatario.apellidos:
#             purchase.apellidos = destinatario.apellidos
#         if destinatario.telefono:
#             purchase.telefono = destinatario.telefono
#         if destinatario.carnet_de_identidad:
#             purchase.carnet_de_identidad = destinatario.carnet_de_identidad
#         if destinatario.correo_electronico:
#             purchase.correo_electronico = destinatario.correo_electronico
#         if destinatario.direccion:
#             purchase.direccion = destinatario.direccion
#         if destinatario.municipio:
#             purchase.municipio = destinatario.municipio
#         if destinatario.instrucciones_entrega:
#             purchase.instrucciones_entrega = destinatario.instrucciones_entrega
#
#
#     session = request.session
#     carro = session.get('carro', {})
#
#     if not carro:
#         return HttpResponseBadRequest("El carrito está vacío.")
#
#     cart_items = carro.items()
#     stock_error_products = []
#     line_items = []
#
#     for item_id, item in cart_items:
#         product = get_object_or_404(Product, pk=item["product_id"])
#         purchase.product.add(product)
#         purchase.guardar_producto(product=product, quantity=item["cantidad"], purchase=purchase)
#         total = total + item["subtotal"]
#
#     purchase.stripe_price = total
#     purchase.save()
#
#     return redirect('solicitud_list')



def purchase_success_cart_view(request):
    purchase_id = request.session.get("purchase_id")
    session = request.session
    carro = session.get('carro', {})
    cart_items = carro.items()


    for item_id, item in cart_items:
        product = get_object_or_404(Product, pk=item["product_id"])
        product.supply = product.supply - item["cantidad"]
        product.save()


    carro = Carro(request)
    carro.limpiar_carro()

    if purchase_id:
        purchase = Solicitud.objects.get(id=int(purchase_id))
        purchase.completed = True
        purchase.save()
        del request.session['purchase_id']

        # Enviar email al usuario si tiene

templates/purchases/cart-table.html
<style>
  /* Estilos para la tabla */
  table {
      width: 100%;
      border-collapse: collapse;
      margin: 2rem 0;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
  }

  /* Encabezado de la tabla */
  th {
      background-color: #f3f4f6; /* Color de fondo suave */
      color: #4b5563; /* Color del texto */
      padding: 1rem;
      text-align: left;
      font-weight: bold;
      border-bottom: 2px solid #e5e7eb; /* Línea inferior */
  }

  /* Celdas de la tabla */
  td {
      padding: 1rem;
      border-bottom: 1px solid #e5e7eb; /* Línea inferior */
      color: #6b7280; /* Color del texto */
  }

  /* Estilo para las filas en hover */
  tr:hover {
      background-color: #f9fafb; /* Color de fondo al pasar el mouse */
  }

  /* Estilo para los enlaces */
  a {
      text-decoration: none; /* Sin subrayado */
      color: #676a6e; /* Color de enlace */
      transition: color 0.3s; /* Transición suave */
  }

  a:hover {
      color: #f0769b; /* Color de enlace al pasar el mouse */
  }

  /* Flexbox para cantidad */
  .flex {
      display: flex;
      align-items: center;
  }

  /* Icono de eliminar */
  svg {
      width: 20px;
      height: 20px;
      cursor: pointer; /* Cambia el cursor al pasar el mouse */
  }

  /* Mensaje de carrito vacío */
  .font-light {
      color: #9ca3af; /* Color más claro para el texto */
  }

  /* Estilo para el card */
  .card {
    max-width: 600px; /* Ancho máximo del card */
      margin: 5px auto; /* Centrar el card horizontalmente */
      padding: 1rem; /* Espaciado interno */
      text-align: center; /* Alinear texto al centro */
      border: 1px solid #e5e7eb; /* Borde del card */
      border-radius: 8px; /* Bordes redondeados */
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1); /* Sombra del card */
  }

  /* Responsividad */
  @media (max-width: 768px) {
    table {
      width: 80%; /* Reducir el ancho de la tabla */
      font-size: 0.8rem; /* Reducir aún más el tamaño de fuente */
    }

    th, td {
      padding: 0.3rem; /* Reducir padding */
    }

    tr {
      margin-bottom: 0.5rem; /* Reducir espaciado entre filas */
      border: 1px solid #e5e7eb; /* Añadir borde a las filas */
    }

    /* Ocultar la columna "Precio" en la vista móvil */
    th:nth-child(3), td:nth-child(3) {
        display: none; /* Ocultar el encabezado y las celdas de Precio */
    }

    td {
      text-align: left; /* Alinear texto a la izquierda */
    }

    /* Eliminar el pseudo-elemento para evitar la repetición del encabezado */
    td[data-label] {
        position: relative; /* Mantener posición relativa si se necesita para otros estilos */
    }
}
</style>

<div class="card">
{% if request.session.carro.items %}
<table class="w-4/5 border-collapse rounded-lg overflow-hidden"> 
    <thead>
      <tr class="bg-gray-200 text-gray-700">
        <th class="px-4 py-3 text-left">Producto</th>
        <th class="px-4 py-3 text-left">Cantidad</th>
        <th class="px-4 py-3 text-left">Precio</th>
        <th class="px-4 py-3 text-left">Subtotal</th>
        <th class="px-4 py-3 text-left">Eliminar</th>
      </tr>
    </thead>
    <tbody>
      {% for key, value in request.session.carro.items %}
      <tr class="border-b border-gray-200 hover:bg-gray-100">
        <td class="px-4 py-3" data-label="Producto">{{ value.name }}</td>
        <td class="px-4 py-3 flex items-center" data-label="Cantidad">
          <a href="{% url 'carro:restar' value.product_id %}" class="mr-2 text-gray-500 hover:text-gray-700">-</a>
          {{ value.cantidad }}
          <a href="{% url 'carro:agregar_carro' value.product_id %}" class="ml-2 text-gray-500 hover:text-gray-700">+</a>
        </td>
        <td class="px-4 py-3" data-label="Precio">${{ value.price }}</td>
        <td class="px-4 py-3" data-label="Subtotal">${{ value.subtotal|floatformat:2 }}</td>
        <td class="px-4 py-3" data-label="Eliminar">
          <a href="{% url 'carro:eliminar' value.product_id %}" class="text-gray-500 hover:text-gray-700">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{% else %}
<div class="px-4 py-3 text-center font-light text-gray-500 dark:text-gray-400">

  Tu carrito de compras está vacío.
</div>
{% endif %}
</div>

templates/purchases/cart.html
{% extends 'base.html' %}

{% block content %}
<style>
* {
    box-sizing: border-box; /* Asegura que el padding y el borde se incluyan en el ancho total */
}

.container-333 {
    padding: 2rem 1rem;
    max-width: 1200px;
    margin: 0 auto;
}

/* Estilos generales para las tarjetas */
.card {
    border-radius: 8px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    padding: 1.5rem;
    
}

/* Alertas */
.alert {
    border: 1px solid #f5c6cb;
    color: #721c24;
    padding: 1rem;
    border-radius: 0.5rem;
    margin-bottom: 1.5rem;
}

/* Títulos */
.titulo {
    color: #333;
    font-size: 2.5rem;
    text-align: center;
    margin-bottom: 1rem;
}

h3 {
    color: #333;
    font-size: 1.5rem;
}

/* Texto */
.font-light {
    color: #666;
}

{#/* Botones */#}
{#button {#}
{#    transition: background-color 0.3s, transform 0.2s;#}
{#}#}
{##}
{#button:hover {#}
{#    transform: translateY(-2px);#}
{#}#}

/* Estilos de botones específicos */
.bg-green-500 {
    background-color: #28a745;
}

.text-gray-700 {
    color: #495057;
}

/* Flexbox */
.flex {
    display: flex;
    flex-wrap: wrap; /* Permitir que los elementos se envuelvan */
}

/* Espaciado */
.mb-4 {
    margin-bottom: 1rem;
}

.mb-6 {
    margin-bottom: 1.5rem;
}



/* Responsividad */
@media (max-width: 768px) {
    .container-333 {
        padding: 1rem; /* Reducir padding en móviles */
        width: 100%; /* Asegurar que el contenedor ocupe el ancho completo */
    }

    .titulo{
        font-size: 2rem;
    }

    .flex {
        flex-direction: column; /* Cambiar a columna en móviles */
        align-items: center; /* Centrar elementos en modo móvil */
        width: 100%; /* Asegurar que el contenedor flex ocupe el ancho completo */
        overflow-x: hidden; /* Evitar el desbordamiento horizontal */
    }

    .card {
        width: 90%; /* Hacer que las tarjetas ocupen el 90% del ancho */
        margin: 10px 0; /* Ajustar márgenes superior e inferior */
        margin-right: 0;
        margin-left: 0;
    }

    .total-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        width: 100%; /* Asegurar que ocupe el ancho completo */
    }

    {#button {#}
    {#    width: 100%; /* Botones ocupan el ancho completo */#}
    {#    height: 40px;#}
    {#}#}

    .button-container {
        display: flex;
        justify-content: center; /* Centra el botón horizontalmente */
        margin-top: 10px; /* Espaciado opcional */
    }
}

</style>

<section class="bg-white dark:bg-gray-900">
   {% if stock_error %}
   <div class="alert" role="alert">
       <strong style="font-weight: bold;">¡Atención!</strong>
       <span>{{ stock_error }}</span>
   </div>
   {% endif %}

   <div class="container-333">
    <div class="text-center mb-8">
        <h2 class="mb-4 titulo">Carrito de compras</h2>
        <p class="font-light text-gray-500 mb-16" style="text-align: center;margin-bottom: 10px">Revisa los productos que has agregado a tu carrito.</p>

    </div>

    <div class="flex flex-center mb-6">
        <!-- Tarjeta para la tabla del carrito -->
            {% include 'purchases/cart-table.html' %}
     

        {% if importe_total_carro %}
        <div class="card" id="card-333">
            <!-- Total del carrito -->
            <div class="total-container mb-4">
                <span style="font-weight: bold; color: #333;">Total:</span>
                <span style="font-weight: bold; color: #333;">${{ importe_total_carro|floatformat:2 }}</span>
            </div>

            <!-- Botón para limpiar el carrito -->
            <div class="mb-4 flex justify-center">
                <a href="{% url 'carro:limpiar' %}" class="bg-white hover:bg-gray-200 text-gray-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline flex items-center">
                    <ion-icon name="trash-outline" style="margin-right: 8px;"></ion-icon>
                    Limpiar Carrito
                </a>
            </div>
            

            <!-- Sección para comprar -->
            <div>
               


                <div class="button-container">

                    <form method="POST" action="{% url 'extra:list_destinatario' %}" class="mb-2">
                        {% csrf_token %}
                        <button type="submit" class="banner-btn">
                            COMPRAR
                        </button>
                    </form>
                </div>

                <!-- Formulario para comprar con Zelle -->
                {# <form method="POST" action="{% url 'purchases:create_solicitud_zelle' %}"> #}
                {#     {% csrf_token %} #}
                {#     <button type="submit" class="banner-btn"> #}
                {#         Comprar con Zelle #}
                {#     </button> #}
                {# </form> #}
            </div>
        </div>
        {% endif %}
    </div>
   </div>
</section>

{% endblock %}

templates/purchases/newcart.html
{% extends 'base.html' %}

{% block content %}
<section class="bg-white dark:bg-gray-900">

   {% if stock_error %}
  <div style="background-color: #f8d7da; border: 1px solid #f5c6cb; color: #721c24; padding: 0.75rem 1.25rem; border-radius: 0.25rem; margin-bottom: 1.5rem;" role="alert">
    <strong style="font-weight: bold;">¡Atención!</strong>
    <span style="display: block; sm: inline;">{{ stock_error }}</span>
  </div>
  {% endif %}

  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
    <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Carrito de compras</h2>
      <p class="font-light text-gray-500 lg:mb-16 sm:text-xl dark:text-gray-400">Revisa los productos que has agregado a tu carrito.</p>
    </div>

    <div class="flex flex-col lg:flex-row gap-8 mb-6 lg:mb-16 items-center justify-center">

      <!-- Tabla del carrito -->
      {% include 'purchases/cart-table.html' %}
  
      {% if importe_total_carro %}
      <div class="w-full lg:w-1/4 flex flex-col justify-end">
          <div class="bg-gray-200 dark:bg-gray-800 p-4 rounded-lg">
              <!-- Total del carrito -->
              <div class="flex justify-between font-bold text-gray-900 dark:text-white mb-4">
                  Total: <span>${{ importe_total_carro|floatformat:2 }}</span>
              </div>
  
              <!-- Botón para limpiar el carrito -->
              <div class="mb-4">
                <a href="{% url 'carro:limpiar' %}" class="bg-white hover:bg-gray-200 text-gray-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Limpiar Carrito
                </a>
            </div>
            
  
              <!-- Sección para comprar -->
              <div>
                  <h3 class="font-bold text-lg mb-2">Opciones de Compra:</h3>
  
                  <!-- Formulario para comprar con Stripe -->
                  <form method="POST" action="{% url 'extra:list_destinatario' %}" class="mb-2">
                      {% csrf_token %}
                      <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                          Comprar con Stripe
                      </button>
                  </form>
  
                  <!-- Formulario para comprar con Zelle -->
{#                  <form method="POST" action="{% url 'purchases:create_solicitud_zelle' %}">#}
{#                      {% csrf_token %}#}
{#                      <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">#}
{#                          Comprar con Zelle#}
{#                      </button>#}
{#                  </form>#}
              </div>
          </div>
      </div>
      {% endif %}
  </div>
  
  </div>
</section>


{% endblock  %}