carro/urls.py
from django.urls import path

from . import views

app_name = 'carro'
urlpatterns = [
    path('agregar/<int:product_id>/', views.agregar_producto, name='agregar'),
    path('agregar_cantidad/<int:product_id>/<int:quantity>/', views.agregar_producto_cantidad, name='agregar_cantidad'),
    path('agregar_carro/<int:product_id>/', views.agregar_producto_desde_carro, name='agregar_carro'),
    path('eliminar/<int:product_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:product_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    path('carro/', views.ver_carro, name='ver_carro'),

    path('contar/', views.contar_carro, name='contar_carro'),



]

extra/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

app_name='extra'
urlpatterns = [

    path('crear_destinatario/', views.crear_destinatario , name='crear_destinatario'),
    path('list_destinatario/', views.lista_destinatarios , name='list_destinatario'),
    path('editar_destinatario/<int:destinatario_id>', views.editar_destinatario , name='editar_destinatario'),
    path('eliminar_destinatario/<int:destinatario_id>', views.eliminar_destinatario , name='eliminar_destinatario'),


]

micro_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuario.views import MyPasswordChangeView
from . import views

urlpatterns = [

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='usuario/reset_pass/password_reset.html'), name='password_reset'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='usuario/reset_pass/complete.html'), name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='usuario/reset_pass/confirm.html'), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='usuario/reset_pass/done.html'), name='password_reset_done'),

    path('administrador/', admin.site.urls, name='admin'),
    path('', include('products.urls')),
    path('carro/', include('carro.urls')),
    path('usuario/', include('usuario.urls')),
    path('extra/', include('extra.urls')),
    path('ventas/', include('ventas.urls')),
    path('pedidos/', include('pedidos_stripe.urls')),



    path('<int:user_id>/password/', MyPasswordChangeView.as_view(),
             name='change_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pedidos_stripe/urls.py
from django.urls import path

from . import views

app_name = 'pedidos_stripe'
urlpatterns = [

    # Compra con stripe
    path('buy_cart/<int:destinatario_id>', views.buy_cart_stripe, name='buy_cart'),
    path('purchases_stripe/', views.pedidos_stripe, name='purchases_stripe'),
    path('ver_solicitud_stripe/<int:purchase_id>', views.purchase_detail, name='ver_solicitud_stripe'),
    path('success_cart/', views.purchase_success_cart_view, name='success_cart'),

    path('stopped/', views.purchase_stopped_view, name='stopped'),


    path('ventas/', views.ventas, name='ventas'),
    path('ver_venta/<int:venta_id>/', views.ver_venta, name='ver_venta'),

    #estdo de pedido
    path('aceptar/<int:purchase_id>/', views.aceptar_pedido, name='aceptar'),
    path('entregar/<int:purchase_id>/', views.entregar_pedido, name='entregar'),
    path('cancelar/<int:purchase_id>/', views.cancelar_pedido, name='cancelar'),




]

extra/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_migrate
from django.dispatch import receiver
from django.apps import apps
from django.contrib.auth.models import  User

from products.models import Product


# Create your models here.

class Municipio(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Destinatario(models.Model):
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=150)
    telefono = models.CharField(max_length=20)
    carnet_de_identidad = models.CharField(max_length=11, blank=True, null=True)  # Opcional
    correo_electronico = models.EmailField(blank=True, null=True)  # Opcional
    direccion = models.CharField(max_length=255)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)  # Selector de municipio
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)  # Relación con el usuario de Django
    instrucciones_entrega = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellidos}"








def crear_municipios_iniciales(sender, **kwargs):
    if kwargs['app_config'].name == 'extra':
        municipios_iniciales = [
            "Santa Clara",
        ]
        for nombre in municipios_iniciales:
            Municipio.objects.get_or_create(nombre=nombre)


post_migrate.connect(crear_municipios_iniciales, sender=apps.get_app_config('extra'))


class Promocion(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to="promociones/", blank=True, null=True)
    imagen_peque = models.ImageField(upload_to="promociones/", blank=True, null=True)
    productos = models.ManyToManyField(Product, related_name='promociones', blank=True)

    def __str__(self):
        return self.nombre

class PromocionText(models.Model):
    texto = models.CharField(max_length=255)


class Delivery (models.Model):
    limit = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=9.99)




class StoreSettings(models.Model):
    header_text = models.CharField(max_length=255)
    is_open = models.BooleanField(default=False)
    facebook_link = models.URLField(max_length=200, blank=True, null=True)
    linkedin_link = models.URLField(max_length=200, blank=True, null=True)
    instagram_link = models.URLField(max_length=200, blank=True, null=True)
    twitter_link = models.URLField(max_length=200, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.header_text

    @classmethod
    def get_instance(cls):
        instance, created = cls.objects.get_or_create(id=1)
        return instance

    def save(self, *args, **kwargs):
        if not self.pk and StoreSettings.objects.exists():
            raise ValidationError('Ya existe un objeto de configuración.')
        super().save(*args, **kwargs)

extra/forms.py
from django import forms
from .models import Destinatario, Municipio

class DestinatarioForm(forms.ModelForm):
    class Meta:
        model = Destinatario
        fields = ['nombre', 'apellidos', 'telefono', 'carnet_de_identidad',
                  'correo_electronico', 'direccion', 'municipio', 'instrucciones_entrega']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-input'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-input'}),
            'telefono': forms.TextInput(attrs={'class': 'form-input'}),
            'carnet_de_identidad': forms.TextInput(attrs={'class': 'form-input'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-input'}),
            'direccion': forms.TextInput(attrs={'class': 'form-input'}),
            'municipio': forms.Select(attrs={'class': 'form-input'}),
            'instrucciones_entrega': forms.Textarea(attrs={'class': 'form-input'}),
        }

extra/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from extra.forms import DestinatarioForm
from extra.models import Destinatario, Delivery
from products.models import Product


# Create your views here.


MAX_DESTINATARIOS_ALCANZADO = "maximo de destinatarios alcanzado"
def crear_destinatario(request):
    deliveries = Delivery.objects.all()
    if request.user.destinatario_set.count() >= 5:
        messages.add_message(request, messages.WARNING, MAX_DESTINATARIOS_ALCANZADO)
        return redirect('extra:list_destinatario')

    if request.method == 'POST':
        form = DestinatarioForm(request.POST)
        if form.is_valid():
            destinatario = form.save(commit=False)
            destinatario.usuario = request.user  # Asignar el usuario actual
            destinatario.save()
            return redirect('extra:list_destinatario')
    else:
        form = DestinatarioForm()
    return render(request, 'extra/crear_destinatario.html', {'form': form,'deliveries': deliveries})


def lista_destinatarios(request):
    if not request.user.is_authenticated:
        messages.warning(request, 'Debes estar registrado para poder realizar compras.')
        return HttpResponseRedirect(reverse('usuario:login'))
    """Vista para mostrar la lista de destinatarios."""
    destinatarios = Destinatario.objects.filter(usuario=request.user)  # Filtra por usuario actual
    query = request.GET.get('q')  # Obtiene el término de búsqueda de la URL

    if query:
        destinatarios = destinatarios.filter(nombre__icontains=query)
    else:
        pass

    session = request.session
    carro = session.get('carro', {})
    stock_error_products = []

    for item_id, item in carro.items():
        product = get_object_or_404(Product, pk=item["product_id"])
        if product.supply < item["cantidad"]:
            stock_error_products.append(product.name)

    if stock_error_products:
        stock_error = "Lo sentimos, no hay suficiente disponibilidad de los siguientes productos: " + ", ".join(
            stock_error_products) + ". Te recomendamos que los retires del carrito para continuar con tu compra."
        context = {
            "stock_error": stock_error
        }
        return render(request, "purchases/cart.html", context)
    else:
        stock_error = None



    context = {
        'destinatarios': destinatarios
    }

    return render(request, 'extra/list_destinatarios.html',context )

def editar_destinatario(request, destinatario_id):
    destinatario = Destinatario.objects.get(pk=destinatario_id)

    if destinatario.usuario != request.user:
        return HttpResponseRedirect(reverse('extra:list_destinatario'))

    if request.method == 'POST':
        form = DestinatarioForm(request.POST, instance=destinatario)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("extra:list_destinatario"))  # Redirige a la lista de destinatarios
    else:
        form = DestinatarioForm(instance=destinatario)

    return render(request, 'extra/editar_destinatario.html', {'form': form})


def eliminar_destinatario(request, destinatario_id):

    destinatario = Destinatario.objects.get(id=destinatario_id)
    if destinatario.usuario != request.user:
        return HttpResponseRedirect(reverse('extra:list_destinatario'))
    destinatario.delete()
    return redirect('extra:list_destinatario')

templates/extra/crear_destinatario.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<style>
    .form-container {
        background-color: #fff;
        padding: 20px;
        margin: 20px auto;
        border-radius: 8px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        max-width: 800px; /* Aumentamos el ancho máximo */
        width: 90%;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .form-title {
        text-align: center;
        margin-bottom: 20px;
        color: #333;
        font-size: 1.5em;
    }

    .form-row {
        display: flex; /* Usar flexbox para las filas */
        justify-content: space-between; /* Espacios entre campos */
        width: 100%; /* Ocupar todo el ancho */
        margin-bottom: 15px; /* Espacio entre filas */
    }

    .form-group {
        flex: 1; /* Cada campo ocupará el mismo espacio */
        margin-right: 10px; /* Espacio entre campos */
    }

    .form-group:last-child {
        margin-right: 0; /* Eliminar margen en el último elemento */
    }

    .form-input, .form-textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        font-size: 1em;
        transition: border-color 0.3s ease;
    }

    .form-input:focus, .form-textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 5px rgba(0, 123, 255, 0.2);
    }

    .form-button {
        background-color: #007bff;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        display: inline-block; /* Cambiado a inline-block */
        margin-right: 10px; /* Espacio entre botones */
        font-size: 1em;
        transition: background-color 0.3s ease;
    }

    .form-button:hover {
        background-color: #0069d9;
    }

    .back-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #3498db;
        color: white;
        border: none;
        border-radius: 5px;
        text-align: center;
        text-decoration: none;
        font-size: 1em;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .back-button:hover {
        background-color: #2980b9;
    }

    .button-container {
        display: flex; /* Usar flexbox para alinear botones */
        justify-content: center; /* Centrar botones */
        width: 100%; /* Ocupar todo el ancho */
        margin-top: 20px; /* Espacio arriba de los botones */
    }

    /* Estilos para pantallas pequeñas */
    @media (max-width: 480px) {
        .form-row {
            flex-direction: column; /* Cambiar a columna en pantallas pequeñas */
        }

        .form-group {
            margin-right: 0; /* Eliminar margen en pantallas pequeñas */
            margin-bottom: 10px; /* Espacio entre campos */
        }

        .form-title {
            font-size: 1.2em;
        }

        .form-input, .form-textarea {
            font-size: 0.9em;
        }

        .form-button, .back-button {
            font-size: 0.9em;
        }
    }
.delivery-options {
        margin-top: 10px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

</style>

<div class="form-container">
    <h1 class="form-title">Agregar Destinatario</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group">{{ form.nombre.label }} {{ form.nombre }}</div>
            <div class="form-group">{{ form.apellidos.label }} {{ form.apellidos }}</div>
            <div class="form-group">{{ form.telefono.label }} {{ form.telefono }}</div>
        </div>
        <div class="form-row">
            <div class="form-group">{{ form.carnet_de_identidad.label }} {{ form.carnet_de_identidad }}</div>
            <div class="form-group">{{ form.correo_electronico.label }} {{ form.correo_electronico }}</div>
            <div class="form-group">{{ form.municipio.label }} {{ form.municipio }}</div>
        </div>
        <div class="form-row">
            <div class="form-group">{{ form.direccion.label }} {{ form.direccion }}</div>
        </div>
        <div class="form-row">
            <div class="form-group">{{ form.instrucciones_entrega.label }} {{ form.instrucciones_entrega }}</div>
        </div>

        <!-- Mostrar opciones de entrega -->
        <div class="form-row">
            <div class="form-group">
                <label>Opciones de Entrega:</label>
                <div class="delivery-options">
                    {% for delivery in deliveries %}
                        <p>{{ delivery.limit }} - ${{ delivery.price }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="button-container">
            <button type="submit" class="form-button">Guardar</button>
            <a href="javascript:history.back()" class="back-button">Volver</a>
        </div>
    </form>
</div>

{% endblock %}

templates/extra/list_destinatario2.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{#<link rel="stylesheet" href="{% static 'css/extra/list_destinatario.css' %}">#}
<style>


.page-title {
    text-align: center;
    font-size: 28px;
    color: #2c3e50;
    margin-bottom: 20px; /* Espacio debajo del título */
}



.search-input:focus {
    border-color: #4CAF50; /* Color de borde al enfocar */
    outline: none; /* Elimina el contorno */
}



.search-button:hover {
    background-color: #45a049;
}




.destinatarios-list {
    list-style: none;
    padding: 0;
    display: flex;
    flex-direction: column; /* Apila los cards verticalmente */
    align-items: center; /* Centra los cards */
}

.card {
    background: white;
    border: 1px solid #ddd;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    padding: 15px;
    margin: 10px 0; /* Espacio entre los cards */
    width: 90%; /* Ocupa el 90% del contenedor */
    max-width: 350px; /* Ancho máximo del card */
    transition: transform 0.2s ease; /* Transición para el efecto hover */
}

.card:hover {
    transform: translateY(-5px); /* Levanta el card al pasar el ratón */
}

.card h2 {
    margin: 0;
    font-size: 20px;
    color: #2c3e50; /* Color del texto */
}

.card p {
    color: #666; /* Color de texto más suave para descripciones */
}

.purchase-button {
    margin-top: 10px;
    padding: 10px;
    background-color: #e67e22; /* Color naranja */
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.purchase-button:hover {
    background-color: #d35400; /* Naranja más oscuro */
}

.action-buttons {
    display: flex;
    justify-content: space-between; /* Espacio entre botones */
    margin-top: 10px;
}

.edit-button, .delete-button {
    background-color: #4CAF50;
    color: white;
    padding: 5px 10px;
    border: none;
    border-radius: 5px;
    font-size: 14px;
    cursor: pointer;
}

.edit-button:hover {
    background-color: #45a049;
}

.delete-button {
    background-color: #e74c3c; /* Color rojo */
}

.delete-button:hover {
    background-color: #c0392b; /* Rojo más oscuro */
}

.search-bar {
    display: flex; /* Usar flexbox para alinear elementos */
    justify-content: center; /* Centrar horizontalmente */
    margin-bottom: 20px; /* Espacio debajo de la barra de búsqueda */
}

.search-input {
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    width: 300px;
    transition: border-color 0.3s ease;
}

.search-button {
    padding: 10px 15px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin-left: 10px; /* Espacio entre el botón de búsqueda y el de agregar */
    transition: background-color 0.3s ease;
}

.add-button {
    margin-left: 10px; /* Espacio entre el botón de búsqueda y el de agregar */
    padding: 8px 15px; /* Tamaño más pequeño */
    background-color: #3498db; /* Color azul */
    color: white;
    border: none;
    border-radius: 5px;
    text-align: center;
    text-decoration: none;
    font-size: 14px; /* Tamaño de fuente más pequeño */
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.add-button:hover {
    background-color: #2980b9; /* Azul más oscuro al pasar el ratón */
}

/* Estilos para pantallas pequeñas */
@media (max-width: 480px) {
    .card {
        width: 100%; /* Ocupa todo el ancho en pantallas pequeñas */
    }
}
</style>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<h1 class="page-title">Lista de Destinatarios</h1>

<div class="search-bar">
    <form method="get" style="display: flex; align-items: center;">
        <input type="text" name="q" placeholder="Buscar por nombre..." class="search-input">
        <button type="submit" class="search-button">Buscar</button>
        <a href="{% url 'extra:crear_destinatario' %}" class="add-button">
            Agregar Destinatario
        </a>
    </form>
</div>

<ul id="destinatarios-list" class="destinatarios-list">
    {% for destinatario in destinatarios %}
    <li class="card" data-nombre="{{ destinatario.nombre|lower }}">
        <div class="card-content">
            <input type="radio" name="destinatario_id" id="destinatario-{{ destinatario.id }}" value="{{ destinatario.id }}" class="destinatario-radio">
            <label for="destinatario-{{ destinatario.id }}">
                <h2 class="destinatario-name">{{ destinatario.nombre }} {{ destinatario.apellidos }}</h2>
                <p class="destinatario-address">{{ destinatario.direccion }}</p>
            </label>
        </div>
        <form method="post" action="{% url 'pedidos_stripe:buy_cart' destinatario.id %}">
            {% csrf_token %}
            <input type="hidden" name="selected_destinatario_id" id="destinatario_id" value="">
            <button type="submit" class="purchase-button">Realizar Compra</button>
        </form>
        <div class="action-buttons">
            <a href="{% url 'extra:editar_destinatario' destinatario.id %}" class="edit-button">Editar</a>
            <a href="{% url 'extra:eliminar_destinatario' destinatario.id %}" class="delete-button">
                <i class="fas fa-times"></i>Eliminar
            </a>
        </div>
    </li>
    {% endfor %}
</ul>

<script src="{% static 'js/extra/list_destinatario.js' %}"></script>


{% endblock %}

templates/extra/list_destinatarios.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{#<link rel="stylesheet" href="{% static 'css/extra/list_destinatario.css' %}">#}
<style>

.info-section {
    background-color: #f9f9f9; /* Fondo claro */
    border: 1px solid #ddd; /* Borde gris claro */
    border-radius: 5px; /* Bordes redondeados */
    padding: 20px; /* Espaciado interno */
    margin: 20px auto; /* Margen superior e inferior, centrado horizontalmente */
    max-width: 600px; /* Ancho máximo */
    width: 90%; /* Ancho adaptable */
    text-align: center; /* Centrar texto */
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); /* Sombra sutil */
}

.info-section h3 {
    margin-bottom: 10px; /* Espacio debajo del encabezado */
    font-size: 24px; /* Tamaño de fuente del encabezado */
    color: #2c3e50; /* Color del texto */
}

.info-section p {
    color: #666; /* Color de texto más suave */
    line-height: 1.5; /* Espaciado entre líneas */
}

/* Estilos para pantallas pequeñas */
@media (max-width: 480px) {
    .info-section {
        padding: 15px; /* Menos espaciado en pantallas pequeñas */
    }

    .info-section h3 {
        font-size: 20px; /* Tamaño de fuente más pequeño en pantallas pequeñas */
    }

    .info-section p {
        font-size: 14px; /* Tamaño de fuente más pequeño para el párrafo */
    }
}

.page-title {
    text-align: center;
    font-size: 28px;
    color: #2c3e50;
    margin-bottom: 20px; /* Espacio debajo del título */
}



.destinatarios-list {
    list-style: none;
    padding: 0;
    display: flex;
    flex-direction: column; /* Apila los cards verticalmente */
    align-items: center; /* Centra los cards */
}

.card {
    background: white;
    border: 1px solid #ddd;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    padding: 15px;
    margin: 10px 0; /* Espacio entre los cards */
    width: 90%; /* Ocupa el 90% del contenedor */
    max-width: 350px; /* Ancho máximo del card */
    transition: transform 0.2s ease; /* Transición para el efecto hover */
}

.card:hover {
    transform: translateY(-5px); /* Levanta el card al pasar el ratón */
}

.card h2 {
    margin: 0;
    font-size: 20px;
    color: #2c3e50; /* Color del texto */
}

.card p {
    color: #666; /* Color de texto más suave para descripciones */
}



.action-buttons {
    display: flex;
    justify-content: space-between; /* Espacio entre botones */
    margin-top: 10px;
}

.edit-button, .delete-button {
    background-color: #4CAF50;
    color: white;
    padding: 5px 10px;
    border: none;
    border-radius: 5px;
    font-size: 14px;
    cursor: pointer;
}

.edit-button:hover {
    background-color: #45a049;
}

.delete-button {
    background-color: #e74c3c; /* Color rojo */
}

.delete-button:hover {
    background-color: #c0392b; /* Rojo más oscuro */
}



.button-container {
    display: flex; /* Usar flexbox para alinear los botones */
    justify-content: center; /* Centrar horizontalmente */
    margin: 20px 0; /* Espacio superior e inferior */
    gap: 10px; /* Espacio entre los botones */
}

.add-button,
.purchase-button {
    padding: 10px 20px; /* Espacio interno */
    border-radius: 5px; /* Bordes redondeados */
    color: white;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.add-button {
    background-color: #3498db; /* Color azul */
    text-decoration: none; /* Sin subrayado */
}

.add-button:hover {
    background-color: #2980b9; /* Azul más oscuro al pasar el ratón */
}

.purchase-button {
    background-color: #e67e22; /* Color naranja */
    border: none; /* Sin borde */
}

.purchase-button:hover {
    background-color: #d35400; /* Naranja más oscuro */
}


/* Estilos para pantallas pequeñas */
@media (max-width: 480px) {
    .card {
        width: 100%; /* Ocupa todo el ancho en pantallas pequeñas */
    }
}
</style>

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<h1 class="page-title">Lista de Destinatarios</h1>


<!-- Sección de Información -->
<div class="info-section">
    <h3>Información</h3>
    <p>Solo se hacen entregas a domicilio en Santa Clara. Las entregas son planificadas con antelación y se le contactará previamente para precisar fecha y hora.</p>
</div>

       <div class="button-container">
    <a href="{% url 'extra:crear_destinatario' %}" class="add-button">
        Agregar
    </a>
    <form id="purchase-form" class="purchase-form" method="post" action="">
        {% csrf_token %}
        <button type="submit" class="purchase-button" onclick="setPurchaseUrl(event)">Realizar Compra</button>
    </form>
</div>


<ul id="destinatarios-list" class="destinatarios-list">
    {% for destinatario in destinatarios %}
    <li class="card" data-nombre="{{ destinatario.nombre|lower }}">
        <div class="card-content">
            <input type="radio" name="destinatario_id" id="destinatario-{{ destinatario.id }}" value="{{ destinatario.id }}" class="destinatario-radio">
            <label for="destinatario-{{ destinatario.id }}">
                <h2 class="destinatario-name">{{ destinatario.nombre }} {{ destinatario.apellidos }}</h2>
                <p class="destinatario-address">{{ destinatario.direccion }}</p>
                <p class="destinatario-phone">{{ destinatario.telefono }}</p> <!-- Añadir aquí el teléfono -->
            </label>
        </div>
        <div class="action-buttons">
            <a href="{% url 'extra:editar_destinatario' destinatario.id %}" class="edit-button">Editar</a>
            <a href="{% url 'extra:eliminar_destinatario' destinatario.id %}" class="delete-button">
                <i class="fas fa-times"></i>Eliminar
            </a>
        </div>
    </li>
    {% endfor %}
</ul>

    <div class="button-container">
    <a href="{% url 'extra:crear_destinatario' %}" class="add-button">
        Agregar
    </a>
    <form id="purchase-form" class="purchase-form" method="post" action="">
        {% csrf_token %}
        <button type="submit" class="purchase-button" onclick="setPurchaseUrl(event)">Realizar Compra</button>
    </form>
</div>

<script>
function setPurchaseUrl(event) {
    event.preventDefault(); // Previene el envío del formulario
    const selectedRadio = document.querySelector('input[name="destinatario_id"]:checked');

    if (selectedRadio) {
        const destinatarioId = selectedRadio.value;
        const form = document.getElementById('purchase-form');
        form.action = "{% url 'pedidos_stripe:buy_cart' '0' %}".replace('0', destinatarioId); // Reemplaza '0' con el ID seleccionado
        form.submit(); // Envía el formulario
    } else {
        alert('Por favor, selecciona un destinatario antes de continuar.');
    }
}
</script>


{% endblock %}